#服务地址
server:
  port: 1010
  address: localhost

spring:
  #项目名
  application:
    name: tfxz
  #数据库的连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cooing
    username: root
    password: password

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true